### ISSUE TITLE
Good project

### ISSUE THREAD

**Issue by WhiskyModz** [AKNoryx28/zygisk-imgui-modmenu#1]
I tested your project and it worked fine. Will you include tools like BNM,Kittymemory in your project?
ı try but my phone die

**Comment by AKNoryx28** [comment]
Good to know. I'm not sure BNM gonna be working since it uses ndk default dlfcn.h, also I want this project for all games not only unity games.
Feel free to contribute

**Comment by AKNoryx28** [comment]
KittyMemory added see https://github.com/AKNoryx28/zygisk-imgui-modmenu/commit/e3e0e68fb2cd97558ca4696fc15d7f96eb2781dd
