### ISSUE TITLE
imgui touch position is incorrect

### ISSUE THREAD

**Issue by opencaw** [AKNoryx28/zygisk-imgui-modmenu#2]
imgui touch position is incorrect, offset to the upper left corner

**Comment by opencaw** [comment]
The touch penetrates the imgui, how to set the touch not to penetrate the imgui

**Comment by reveny** [comment]
You can hook unity's nativeInjectEvent to get correct input positions

**Comment by AKNoryx28** [comment]
it is an imgui scaling issue when screen game resolution not the same with device resolution in unity's games, for now the only fix that i know force set resolution using the `SetResolution` hook in the `Screen` class

**Comment by ghost** [comment]
how to fix this issue for games that arent unity based
