### ISSUE TITLE
unable to compile

### ISSUE THREAD

**Issue by LIBBBhhh** [AKNoryx28/zygisk-imgui-modmenu#5]
compile error: requires updated version cmaker 3.25.2 which is not available in android studio via github also fails to compile the module

**Comment by LIBBBhhh** [comment]
And if I change the version in the file Cmaker Gives an error, I need to fix this problem I fiddled with the source code for half a day and did not fix anything

**Comment by AKNoryx28** [comment]
Checkout new commit and try build again https://github.com/AKNoryx28/zygisk-imgui-modmenu/commit/bc6772ad82183b3c8cc1fcad0889e77db8794d73

**Comment by LIBBBhhh** [comment]
it works, the module is ready successfully thank you I close the topic
