### ISSUE TITLE
Dobbyhook error 

### ISSUE THREAD

**Issue by QPLAYid** [AKNoryx28/zygisk-imgui-modmenu#6]
DobbyHook((void *)getAbsoluteAddress("libil2cpp", "0x133949"), (void *)new, (void **)old_new);

Declarated

**Comment by AKNoryx28** [comment]
Explain in more detail sir
Maybe ur not reference "old_new"
```c++
DobbyHook((void *)getAbsoluteAddress("libil2cpp", "0x133949"), (void *)new, (void **)&old_new);
```

**Comment by QPLAYid** [comment]
https://www.mediafire.com/file/b4x2av2h9kum013/hack.cpp/file 


That hack.cpp 
Dobby hook declarate fro github action

**Comment by QPLAYid** [comment]
> Explain in more detail sir Maybe ur not reference "old_new"
> 
> ```c++
> DobbyHook((void *)getAbsoluteAddress("libil2cpp", "0x133949"), (void *)new, (void **)&old_new);
> ```

/home/runner/work/zygisk-imgui-modmenu/zygisk-imgui-modmenu/module/src/main/cpp/hack.cpp:135:19: error: use of undeclared identifier 'getAbsoluteAddress'
  DobbyHook((void *)getAbsoluteAddress("libil2cpp.so", 0x133949), (void *)ambus, (void **)&old_ambus);
